name: Emoji Replacer Auto Update

on:
  # 定时触发，每周日凌晨2点执行
  schedule:
    - cron: '0 2 * * 0'
  # 也支持手动触发
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 获取完整历史记录

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 缓存依赖
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tqdm

      # 运行 Emoji 替换脚本
      - name: Run Emoji Replacer
        run: |
          cd emojis
          python emoji_replacer.py -r -v --incremental --report ../emoji_report.txt

      # 检查文件变更并提交
      - name: Commit changes
        run: |
          # 配置 Git 用户信息
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # 检查是否有文件变更
          if [[ -n $(git status --porcelain) ]]; then
            # 添加所有变更文件
            git add .
            # 提交变更
            git commit -m "🤖 Auto-update: Replace Emojis with Android-compatible versions"
            # 推送到远程仓库
            git push
            echo "✅ Changes committed and pushed successfully"
          else
            echo "❎ No changes to commit"
          fi
