name: 自动替换Emoji

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-emojis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install --upgrade pip
      - name: Run auto_update_emojis.py
        run: python emojis/auto_update_emojis.py
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --cached --quiet || git commit -m "Auto update emojis in JSON files"
          git push
