name: Sync Subfolder Projects
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout collecting repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以便合并

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          echo "Git setup complete"

      - name: Sync each subfolder with its external repository
        run: |
          # 定义子文件夹和对应的外部仓库
          declare -A projects=(
            ["alantang1977"]="https://github.com/alantang1977/X.git"

          )

          for folder in "${!projects[@]}"; do
            external_repo="${projects[$folder]}"
            echo "Starting sync for folder: $folder with $external_repo"

            # 检查子文件夹是否存在
            if [ ! -d "$folder" ]; then
              echo "Error: Folder $folder does not exist in collecting-repo"
              continue
            fi

            # 克隆外部仓库到临时目录
            temp_dir=$(mktemp -d)
            echo "Cloning $external_repo to $temp_dir"
            if ! git clone --depth 1 "$external_repo" "$temp_dir"; then
              echo "Error: Failed to clone $external_repo"
              continue
            fi

            # 同步外部仓库到子文件夹
            echo "Syncing $external_repo to $folder"
            cd -
            rsync -av --delete --exclude '.git' "$temp_dir/" "./$folder/" || {
              echo "Error: rsync to $folder failed"
              continue
            }
            git add "$folder"
            if ! git diff --staged --quiet; then
              echo "Changes detected, committing to repo"
              git commit -m "Sync changes from $external_repo to $folder" || {
                echo "Error: Git commit failed for $folder in collecting-repo"
                continue
              }
              echo "Pushing to collecting-repo"
              git push origin main || {
                echo "Error: Git push failed for collecting-repo"
                continue
              }
            else
              echo "No changes to commit for $folder in collecting-repo"
            fi

            rm -rf "$temp_dir"
            echo "Completed sync for $folder"
          done
